---
language: python

dist: trusty

python:
  - "3.7"

addons:
  apt:
    packages:
      - curl

install:
  - pip install --process-dependency-links .[dev]
  - pip install codacy-coverage
  - curl -X POST --header "Private-Token: ${GITLAB_TOKEN:-PLEASE DO NOT HATE ME}" 'https://gitlab.com/api/v4/projects/GrafeasGroup%2Ftor/mirror/pull' || true

script:
  - pytest --cov=tor

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
