---
language: python

dist: trusty

python:
  - "3.6"
  - "3.6.5"
  - "3.7.2"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.6.5
    - python: 3.7.2
    - python: nightly

before_install:
  - pip install poetry

install:
  - poetry install --no-dev --extras ci
  # - poetry add mypy
  # - poetry add black --allow-prereleases

script:
  - pytest --cov=tor
  # - mypy .
  # - black .

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
