---
language: python

dist: xenial

python:
  - "3.6"
#   - "3.7"
#   - "nightly"
#
# matrix:
#   allow_failures:
#     - python: 3.7
#     - python: nightly

before_install:
  - pip install poetry

install:
  - poetry install --no-dev --extras ci

script:
  - poetry run pytest --cov=tor
  # - poetry run mypy .
  # - poetry run black .

after_success:
  - poetry run coverage xml
  - poetry run python-codacy-coverage -r coverage.xml
