---
language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.8
    - python: 3.8-dev
    - python: nightly

install:
  - pip install poetry
  - pip install tox
  - pip install tox-travis
  - pip install codacy-coverage

script:
  - tox

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
