---
language: python

dist: trusty

python:
  - "3.7-dev"

addons:
  apt:
    packages:
      - curl

install:
  - 'curl -X POST --header "Private-Token: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/GrafeasGroup%2Ftor/mirror/pull"'
  - pip install --process-dependency-links .[dev]
  - pip install codacy-coverage

script:
  - pytest --cov=tor

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
