---
language: python

dist: trusty

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: nightly

install:
  - pip install --process-dependency-links .[dev]

script:
  - pytest --cov=tor

after_success:
  - bash <(curl -s https://codecov.io/bash)
